import product2 from "./../assets/NewArrivals/product1.png";
import product22 from "./../assets/NewArrivals/product2.png";
import product33 from "./../assets/NewArrivals/product3.png";
import product44 from "./../assets/NewArrivals/product4.png";
import product1 from "./../assets/NewArrivals/product5.png";
import product3 from "./../assets/NewArrivals/product6.png";
import product4 from "./../assets/NewArrivals/product7.png";
import product11 from "./../assets/newproduct.png";

export const productsData = [
  {
    id: 1,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product1}`,
    review: 83,
    price: 42.0,
    size: false,
    quick_view: true,
    color: true,
    stock: false,
    new_in: false,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product2}`,
    review: 82,
    price: 32.0,
    size: true,
    quick_view: false,
    stock: true,
    new_in: false,
    rating: 4.4,
    color: false,
  },
  {
    id: 3,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product3}`,
    review: 73,
    price: 82.0,
    size: false,
    quick_view: true,
    color: true,
    stock: true,
    new_in: false,
    rating: 4.0,
  },
  {
    id: 4,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product4}`,
    review: 65,
    price: 58.0,
    size: false,
    quick_view: true,
    color: true,
    stock: true,
    new_in: true,
    rating: 5.0,
  },
  {
    id: 5,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product11}`,
    review: 50,
    price: 38.99,
    size: true,
    quick_view: false,
    stock: true,
    new_in: false,
    rating: 5.0,
    color: false,
  },
  {
    id: 6,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product22}`,
    review: 38,
    price: 62.99,
    size: true,
    quick_view: false,
    stock: true,
    new_in: false,
    rating: 4.8,
    color: false,
  },
  {
    id: 7,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product33}`,
    review: 13,
    price: 59.0,
    size: false,
    quick_view: true,
    color: true,
    stock: true,
    new_in: true,
    rating: 4.9,
  },
  {
    id: 8,
    name: "Leather Gloves",
    desc: "Perfect mint green",
    image: `${product44}`,
    review: 48,
    price: 32.0,
    size: false,
    quick_view: true,
    color: true,
    stock: true,
    new_in: false,
    rating: 4.1,
  },
];
